on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'  # Specify the Flutter version you want to use

      - name: Build Flutter web app
        run: flutter build web --dart-define API_KEY=${{ secrets.API_KEY }}

      # Add additional steps like testing and code analysis here

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: build/web