name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        # with:
          # customArgs: --dart-define="API_KEY=${{ secrets.MY_SECRETS }}"
          # baseHref: /detective/
          # workingDir: github_page